%bcond_without tests
%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/cargotest/.*$
%global __requires_exclude_from ^/opt/ros/cargotest/.*$

%global __cmake_in_source_build 1

Name:           ros-cargotest-ament-cmake-core
Version:        2.9.0
Release:        1%{?dist}%{?release_suffix}
Summary:        ROS ament_cmake_core package

License:        Apache License 2.0
URL:            https://index.ros.org/p/ament_cmake_core/#cargotest
Source0:        %{name}-%{version}.tar.gz

Requires:       cmake3
Requires:       python%{python3_pkgversion}-catkin_pkg
Requires:       ros-cargotest-ament-package
BuildRequires:  cmake3
BuildRequires:  python%{python3_pkgversion}-catkin_pkg
BuildRequires:  ros-cargotest-ament-package
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%description
The core of the ament buildsystem in CMake. Several subcomponents provide
specific funtionalities: * environment: provide prefix-level setup files *
environment_hooks: provide package-level setup files and environment hooks *
index: store information in an index and retrieve them without crawling *
package_templates: templates from the ament_package Python package *
symlink_install: use symlinks for CMake install commands

%prep
%autosetup -p1

%build
# Needed to bootstrap since the ros_workspace package does not yet exist.
export PYTHONPATH=/opt/ros/cargotest/lib/python%{python3_version}/site-packages

# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/cargotest/setup.sh" ]; then . "/opt/ros/cargotest/setup.sh"; fi
mkdir -p .obj-%{_target_platform} && cd .obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/cargotest" \
    -DAMENT_PREFIX_PATH="/opt/ros/cargotest" \
    -DCMAKE_PREFIX_PATH="/opt/ros/cargotest" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
%if !0%{?with_tests}
    -DBUILD_TESTING=OFF \
%endif
    ..

%make_build

%install
# Needed to bootstrap since the ros_workspace package does not yet exist.
export PYTHONPATH=/opt/ros/cargotest/lib/python%{python3_version}/site-packages

# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/cargotest/setup.sh" ]; then . "/opt/ros/cargotest/setup.sh"; fi
%make_install -C .obj-%{_target_platform}

%if 0%{?with_tests}
%check
# Needed to bootstrap since the ros_workspace package does not yet exist.
export PYTHONPATH=/opt/ros/cargotest/lib/python%{python3_version}/site-packages

# Look for a Makefile target with a name indicating that it runs tests
TEST_TARGET=$(%__make -qp -C .obj-%{_target_platform} | sed "s/^\(test\|check\):.*/\\1/;t f;d;:f;q0")
if [ -n "$TEST_TARGET" ]; then
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/cargotest/setup.sh" ]; then . "/opt/ros/cargotest/setup.sh"; fi
CTEST_OUTPUT_ON_FAILURE=1 \
    %make_build -C .obj-%{_target_platform} $TEST_TARGET || echo "RPM TESTS FAILED"
else echo "RPM TESTS SKIPPED"; fi
%endif

%files
/opt/ros/cargotest

%changelog
* Thu Jun 18 2026 Chris Lalancette <clalancette@gmail.com> - 2.9.0-1
- Autogenerated by Bloom

